### PR TITLE
docs: non-ascii locales must specify a content-type

### PR DESCRIPTION
**Pull request by regisb**
See: https://discuss.overhang.io/t/translating-login-registration-page/1378/3

This should also address issue #410.

This is ready for review @overhangio/tutor-developers

### CODE REVIEW

**Comment by regisb** [comment]
ping @overhangio/tutor-developers?

**Comment by pcliupc** [comment]
Looks good to me.

**Comment by regisb** [comment]
Thanks @pcliupc! FYI you can explicitely review the changes by hitting the "review changes" button in the "files changed" menu.

**Comment by pcliupc** [comment]
@regisb  sure, I will follow this style.

**Pull request merged**
