### PR TITLE
Docs should better explain how to renew SSL/TLS certificates

### PR DESCRIPTION
**Pull request by cacciaresi**

### CODE REVIEW

**Comment by regisb** [comment]
See the relevant conversation here: https://discuss.overhang.io/t/renew-lets-encrypt-cert-failing/268/4

**Comment by cacciaresi** [comment]
@regisb do you think that we should add more info to this PR?

**Comment by regisb** [comment]
This is fine, sorry about the delay.

**Comment by cacciaresi** [comment]
@regisb :heart: no issues, just wanted to know if we need to add something else. thanks!

**Pull request merged**
