### PR TITLE
WIP: Add backup and restore commands to the makefile

### PR DESCRIPTION
**Pull request by frob**
After reading #87 I realized that there seemed to be no non-filesystem based backup provisions. This MR adds them.

## Adds the Makefile commands:

 - `backup-lms`
 - `backup-cms`
 - `restore-lms`
 - `restore-cms`

The restore commands allow users to specify the `DUMP` used for the restoration.

### CODE REVIEW

**Comment by frob** [comment]
Documentation is coming.

**Comment by frob** [comment]
Okay, documentations is done. I have rebased off regisb/master I am doing some final testing before removing WIP.

**Comment by regisb** [comment]
This is a useful feature. I like how the `backup` and `restore/restore-dangerous` commands work together. My feeling is that the bash commands are a bit brittle, and too difficult to understand. Moreover, the backup commands only work for the openedx database, and not for the xqueue and the notes databases. But this PR is a good starting point. I'll have some time to work on this next week, during the Christmas holidays. In particular, I'd suggest renaming the make commands to something like `backup-openedx-sql` and `backup-openedx-mongodb`, since the lms and the cms essentially share the same database. Are you ok with that?

**Comment by frob** [comment]
Good to know [about the other databases]. I was basing this off of the issue #87 so I thought those where the only two DBs that need the backup feature. I agree with you about the bash commands but I cannot think of a good way to do it in make and breaking it into shell scripts seemed a bit obfuscating.

The main difficulty is the mongp db backup. It would be easier if the mongodump utility was on the lms/cms images, but its not and I like to avoid adding dependencies for utilities. Another option to my approach is to just use the base ubuntu image and add everything we need in a single inline docker command; instead of relying on docker-compose.

**Comment by frob** [comment]
I am looking through the services, I see these possibly needing backups:

- [x] lms
- [x] cms
- [ ] xqueue
- [ ] notes
- [ ] forum

did I miss anything?

**Comment by regisb** [comment]
@frob I don't know if you've resumed work on this, but I think it's better if you wait a little until the release of tutor v3. A lot of things are going to change, and you may have to throw away most of the things you did.

**Comment by frob** [comment]
Nope, I have been preoccupied. Thanks for the heads-up as I was going to
get back at the end of the week.

**Comment by regisb** [comment]
Making backups is not a tutor command, but there are instructions for it: https://docs.tutor.overhang.io/local.html?#backups-migrating-to-a-different-server
I believe this is sufficient, for now. Please open an issue if you think otherwise.

**Pull request closed without merging**
