### PR TITLE
fix: remove trailing slashes in volume paths for docker-compose v2 compatibility

### PR DESCRIPTION
**Pull request by BbrSofiane**
Remove trailing slashes in volume paths for docker-compose v2 compatibility.

@overhangio/tutor-developers this is ready for review.

### CODE REVIEW

**Review by regisb — CHANGES_REQUESTED** [review]
Looking good! Can you please add a line to the changelog to explain that this resolves a WSL issue? Also please add "close #522" to the commit message to automatically close the issue on merge.

**Comment by BbrSofiane** [comment]
@regisb whoops yep I forgot the changelog!

**Comment by iamCristYe** [comment]
better update https://github.com/overhangio/tutor/blob/master/docs/dev.rst#override-docker-compose-volumes as well?

**Comment by regisb** [comment]
Yes @BbrSofiane I think that @iamCristYe is right, we should update the docs as well.

**Comment by BbrSofiane** [comment]
Good spot @iamCristYe

**Review by regisb — APPROVED** [review]

**Pull request merged**
