### PR TITLE
proposal/idea: reorganize documentation for better discoverability

### PR DESCRIPTION
**Pull request by brian-smith-tcril**
## Backstory

While learning how to develop tutor plugins, I found it somewhat difficult to find the information I was looking for in the current documentation without knowing the proper search terms.

## What is this PR?

This PR is my (draft/work in progress/looking for feedback) proposal for a way to possibly reorganize the existing documentation to allow for greater discoverability

## Is there an easy way to see the proposed changes?

Yes! I temporarily added a github actions workflow to my fork that is publishing the documentation from this branch to github pages. You can check it out here: https://brian-smith-tcril.github.io/tutor/

## What's left to do?
- [x] Get my initial thoughts on reorganization out in the form of a PR code changes
- [x] Figure out an easy way to get feedback from people who don't feel like pulling this branch down and building docs locally
- [ ] Get feedback from everyone
- [ ] Come to an agreement on what changes should be made
- [ ] Implement agreed-upon changes
- [ ] Clean up the PR (rebase to remove WIP commit messages, remove github pages workflow)
- [ ] Turn off github pages on my fork
- [ ] Final review
- [ ] Hopefully get something everyone is happy with merged in!

### CODE REVIEW

**Comment by regisb** [comment]
Hi @brian-smith-tcril, is this PR still relevant?

**Comment by brian-smith-tcril** [comment]
@regisb absolutely! As I mentioned in my original comment, this PR is meant to be a jumping off point for a conversation around how to best organize the documentation.

A simple view of the difference can be seen in the navigation links (left is my fork, right is docs.tutor.overhang.io)

image

I'd love to hear how others feel about these proposed changes!

**Comment by regisb** [comment]
I think you're on the right track and I love the fact that you're working on docs. Please continue. Let me know when this is ready for review.

**Comment by regisb** [comment]
Hey Brian, I really like where you're going and I wouldn't like to lose the momentum. Do you think you'll be able to set time aside soon to work on this PR? You shouldn't try to get feedback from too many people, just go with what you think is best and we'll discuss your changes here.

**Comment by brian-smith-tcril** [comment]
Yes! Sorry I've let it sit for so long. I'll make sure to get it rebased and ready for review ASAP!

**Pull request closed without merging**
