### PR TITLE
run tutor on raspberry pi 4

### PR DESCRIPTION
**Pull request by hiroTochigi**
## Attempt to run openedx on Raspberry Pi 4 by tutor.
However, I mistook to push this pull request to upstream.
Sorry for bothering for it.

### CODE REVIEW

**Comment by regisb** [comment]
Wait @hiroTochigi we need to talk. Are you running Tutor on a Raspberry Pi 4? Did you get it to work? I would be very much interested in learning about your efforts -- whether or not you succeeded, and the reason why you are attempting this.

**Comment by hiroTochigi** [comment]
Thank you for having your comment on the pull request.
I do not finish it yet.
However, I made the pre-released executable file.
https://github.com/ole-vi/tutor-rpi/releases/tag/v10.0.10-rpi
My Raspberry Pi 4 can run Tutor.

I am doing this project as my Virtual Internship of [OLE (Open Learning Exchange)](https://www.ole.org/)
We are develop software [Treehouses](https://github.com/treehouses), which host various LMS ([Kolibri](https://learningequality.org/kolibri/), [Moodle](https://moodle.org/), [Planet](https://github.com/open-learning-exchange)) on Raspberry Pi.
We plan to integrate Tutor into Treehouses.
Tutor is very awesome software.
Binary Tutor file is not executable on Raspberry Pi, but I can use it on Raspberry Pi because I could build it without any troubles. 
 
All Docker Images but Nginx are not executable on Raspberry Pi.
I built all of these images on my Raspberry Pi.
Some images work on Raspberry Pi without tweak, but more than half of images need to be tweaked.

**Comment by regisb** [comment]
Thanks for the background information @hiroTochigi! Can you please tell me about if you manage to get Tutor to run on a Raspberry Pi? I have one sitting on my desk and I'd love to try it out.

**Comment by hiroTochigi** [comment]
Yes, I will.
I verify that Tutor can work on Raspberry Pi 4 with 8G RAM.
However, it is not yet to implement to host OpenEdx on Tor Network by Tutor.

**Comment by ak00001** [comment]
@hiroTochigi : this project is really cool, congratulations. I have a stack of RPi3 running Docker Swarm. You think they'd be up to the task of running Tutor? 

You're mentioning hosting Open edX on the Tor Network. Is the goal for the rpi to work as a Tor relay and serve educational content?

**Comment by regisb** [comment]
Where's the emoji for "ambitious" :stuck_out_tongue:? :sunglasses:

**Comment by hiroTochigi** [comment]
@ak00001 I am not sure whether RPi3 can handle to host Open edx.
 
Yes, our goal is to run Open edX on the Tor Network.
I am working for Treehouses, one of the main software of OLE (Open Learning Exchange), being able to execute Tutor and configure Open edX automatically on the Tor Network.

**Comment by ak00001** [comment]
@hiroTochigi How is this project coming along? Did you manage to get something up and running?

**Comment by hiroTochigi** [comment]
@ak00001 
image
At least RPI4 can host OpenEdx on Tor network.

**Comment by regisb** [comment]
@hiroTochigi This is awesome! Would you care to make a write-up on [the forums](https://discuss.overhang.io) with your experience?

**Comment by hiroTochigi** [comment]
Yes. Definitely.
Where should I make the write-up? Is the Tutor section adequate?
There are three sections in the Tutor forums.
Also, is it enough that the write-up informs why I did it, how I did it, and how users use it?

**Comment by regisb** [comment]
> Where should I make the write-up? Is the Tutor section adequate?

Sure!

> Also, is it enough that the write-up informs why I did it, how I did it, and how users use it?

This is interesting information, yes!

**Comment by regisb** [comment]
@hiroTochigi any news? Do you think you could make a quick writeup to describe your approach? If it's too rough for public consumption you can also send it to me personally.

**Comment by hiroTochigi** [comment]
@regisb 
I am really sorry for the lack of any response.
I have not been working on this project for a while.
I have made a short description of this project and attached it on this closed pull request.
[Tutor for Raspberry Pi 4.odt](https://github.com/overhangio/tutor/files/7491821/Tutor.for.Raspberry.Pi.4.odt)

**Comment by regisb** [comment]
This is really useful feedback @hiroTochigi, thanks a lot!

**Pull request closed without merging**
