### PR TITLE
feat: Add config parameters for k8s volume sizes

### PR DESCRIPTION
**Pull request by foadlind**
Today, the storage size for Persistent Volume Claims for services like
MongoDB and MySQL are hard-coded in Tutor. Make those configurable by
setting template variables in `defaults.yaml`.
This gives Tutor users the option to define volume sizes in their
`config.yml`.

Reference discussion: https://discuss.openedx.org/t/adding-configuration-parameters-for-persistent-volume-claim-sizes-in-tutor-k8s/7327

### CODE REVIEW

**Review by fghaas — APPROVED** [review]
+1 on this change. The 5 GiB size for MongoDB in particular will be a problem for anyone migrating an existing Open edX codebase into `tutor k8s`, so making this configurable is absolutely a welcome addition.

**Comment by foadlind** [comment]
@regisb That will certainly make it easier for users to change K8s objects with plugins. Is anyone working on making these changes in Tutor? Otherwise I can take it on.

**Comment by regisb** [comment]
It would be fantastic if you could work on it @foadlind.

**Comment by CodeWithEmad** [comment]
is this PR abandoned?
It's almost time to celebrate its first anniversary!

**Comment by CodeWithEmad** [comment]
I completely agree. Therefore, we can consider this matter resolved.

**Comment by fghaas** [comment]
Yes, we do use a YAML plugin with a `k8s-override` patch for this purpose now. Side note: please see https://github.com/kubernetes-sigs/kustomize/issues/5052 for an issue related to `patchesStrategicMerge` deprecation/removal.

**Comment by kumarviresh25** [comment]
hi i have  created a plugin k8s-override and after saving i can see the increased volume in override. i want to ask i have to apply override.yml file and thn restart thn my mongo volume will be increased . one more thing i have created another plugin for memory increment of lms so i have used k8s-deployments i can see in deployments.yml with update after this i am running tutor k8s start it is throwing error Namespace already exists: skipping creation.
kubectl apply --kustomize /home/ubuntu/eks/envtutor/env --wait --selector app.kubernetes.io/component=volume
error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 20: mapping key "apiVersion" already defined at line 1
  line 21: mapping key "kind" already defined at line 2
  line 22: mapping key "metadata" already defined at line 3
  line 27: mapping key "spec" already defined at line 14
Error: Command failed with status 1: kubectl apply --kustomize /home/ubuntu/eks/envtutor/env --wait --selector app.kubernetes.io/component=volume
@regisb @foadlind pl check once.

**Comment by regisb** [comment]
Resolved by the "k8s-override" patch. Please re-open if you think this PR is still necessary.

**Pull request closed without merging**
