### PR TITLE
fix: save config and env on `plugins enable/disable`

### PR DESCRIPTION
**Pull request by regisb**
This replaces https://github.com/overhangio/tutor/pull/917/

### CODE REVIEW

**Comment by regisb** [comment]
@fghaas Would it make sense to add a `--no-save-env` (or similar) option to `tutor plugins enable/disable`?

**Comment by fghaas** [comment]
Good question. _Most of the time,_ users would want automatic `config save`, particularly if the plugin requires a `config.yml` variable to be initialized. So I think Tutor does the "right" thing by default in v17, except if we're applying an excessively strict interpretation of [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Would a toggle to turn it off be useful, or would it be more likely to be a footgun? I really don't know.

**Comment by regisb** [comment]
Let's do nothing for now. If you (or anyone else) later think it's important we can decide to add a toggle.

**Comment by fghaas** [comment]
That works for me!

**Pull request merged**
