### PR TITLE
Add option to patch lms and cms nginx server block

### PR DESCRIPTION
**Pull request by mrtndwrd**
As proposed in https://discuss.overhang.io/t/editing-nginx-lms-and-cms-conf/1096

This allows yaml plugins to define a `nginx-lms` and `nginx-cms` block. The block gets inserted in the lms and cms server configuration for nginx. For example, this plugin proxies requests to `/js-components` to an external website (needs `ca-certificates` bundle installed on the host machine):

```
cat tutor-plugins/totem-proxy.yml 
---
name: totem-proxy
version: 0.1.0
patches:
  nginx-lms: |
    location /js-components/ {
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        proxy_pass https://totem-project.org/js-components/;
        proxy_ssl_server_name on;
    }

  nginx-cms: |
    location /js-components/ {
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        proxy_pass https://totem-project.org/js-components/;
        proxy_ssl_server_name on;
    }

  local-docker-compose-nginx-volumes: |
    - /etc/ssl/certs:/etc/ssl/certs:ro
```

### CODE REVIEW

**Comment by regisb** [comment]
Looks good! Can you please add a note to the CHANGELOG? (in the "unreleased" section).

**Comment by mrtndwrd** [comment]
Yes, sure! I amended the original commit to include that. 

Maybe it's a good idea to add this to your `CONTRIBUTING.rst` by the way :)

**Comment by regisb** [comment]
Thanks for your contribution @mrtndwrd! 

> Maybe it's a good idea to add this to your CONTRIBUTING.rst by the way :)

It is! https://github.com/overhangio/tutor/commit/e6176e293c2e5f3d13be331c6ff23a07c0665a19#diff-f94b76ecc373d484f1bf8b218e690f92be03225e3a5940f6f0d392b816783901

**Comment by mrtndwrd** [comment]
Thanks for the super quick merge! And thanks for clarifying where to find the contribution guidelines as well :)

**Pull request merged**
