### PR TITLE
wrong author on my last PR

### PR DESCRIPTION
**Pull request by CodeWithEmad**
Hi @regisb 
I used my Gitlab account name and email on the incluster PR.
is it possible to merge this to change the author name?

### CODE REVIEW

**Comment by regisb** [comment]
Merging this new PR is not going to amend existing commits. I will need to manually amend the commit and push-force both the master and the nightly branches. Can I ask why you need to make this change? Is it to avoid publishing your email address?

**Comment by CodeWithEmad** [comment]
I was thinking that merging the amended commits might do the trick.
In addition, I aspire to be one of the top tutor contributors, aside from the email aspect. However, I understand if it takes up too much of your time and it's not necessary.

**Comment by regisb** [comment]
No worries, I amended your name and email address in your last commits: https://github.com/overhangio/tutor/commits?author=CodeWithEmad

**Comment by CodeWithEmad** [comment]
I truly appreciated it.

**Pull request closed without merging**
