### PR TITLE
fix: apply LTI 1.3 XBlock patch fix 3.4.7 over nutmeg.1

### PR DESCRIPTION
**Pull request by ormsbee**
The actual merge of this into open-release/nutmeg.master is here:
  https://github.com/openedx/edx-platform/pull/30716

### CODE REVIEW

**Comment by ormsbee** [comment]
@regisb: cherry-picking the [LTI fix](https://github.com/openedx/edx-platform/pull/30716) over nutmeg.

**Review by regisb — APPROVED** [review]
Awesome, thanks!

**Comment by ormsbee** [comment]
Now I make another one to bump the version for a release?

**Comment by regisb** [comment]
I usually take care of that at some point but if you need a new release now, sure you can make another pr.

**Comment by ormsbee** [comment]
Yeah, this is the tail end of a long trail of yak shaving to get Nutmeg certified for LTI 1.3–something I really want to get over and done with at this point. I'll make that version bump PR now.

**Comment by ormsbee** [comment]
Version bump PR: https://github.com/overhangio/tutor/pull/702

@regisb: Nice contribution docs and setup on this project, btw. It's probably got the most thoughtful release practices of any of the repos in the project I've seen.

**Pull request merged**
