### PR TITLE
chore: remove Python 3.8 references

### PR DESCRIPTION
**Pull request by DawoudSheraz**
Achieves part of https://github.com/overhangio/tutor/issues/1129, 

- Update Python 3.8 references to 3.9
- Update Github actions to use 3.9
- Ensure tests are working as expected on 3.9
- compile and upgrade requirements on 3.9 base
- `make bundle` and `make ci-test-bundle` are running on 3.9

### CODE REVIEW

**Comment by regisb** [comment]
You will also need to make the following changes:

1. Bump sphinx version in requirements/docs.in
2. Remove some items from `nitpick_ignore` in docs/conf.py.

**Comment by DawoudSheraz** [comment]
> You will also need to make the following changes:
> 
> 1. Bump sphinx version in requirements/docs.in
> 2. Remove some items from `nitpick_ignore` in docs/conf.py.

I have updated the docs.in the requirements file. As for nitpick_ignore, there were no Python 3.8 specific ignored expressions. I tried removing a few items before Python 3.10 comment but removing them caused the docs to fail locally.

**Review by regisb — APPROVED** [review]
lgtm!

**Review by kdmccormick — COMMENTED** [review]
I did not review, but Regis's review should be sufficient. 👍🏻

**Pull request merged**
