### PR TITLE
fix: uwsgi closed connection

### PR DESCRIPTION
**Pull request by Ian2012**
### Description

This PR modifies the uwsgi config file to improve lms/cms deployments. It follows the recommendations from [Bloomberg uWSGI production deployment](https://www.bloomberg.com/company/stories/configuring-uwsgi-production-deployment/) and solvesa 502 error based on the issue: https://github.com/unbit/uwsgi/issues/2133.

### The issue

Sometimes after a POST request, the connection between Caddy and the LMS/CMS pod is closed prematurely which returns a 502 error. this is fixed by setting `http-keepalive` plus manually adding the header `Connection: Keep-Alive`. Please take a look at this comment for more context: https://github.com/unbit/uwsgi/issues/1097#issuecomment-1323662862.

### Improvements

Following the best practices for production uwsgi deployments in docker we applied the following changes:

```
# Better startup/shutdown in docker
die-on-term = true
lazy-apps = false
need-app = true
no-defer-accept = true

# Other settings
master = true
py-call-osafterfork = true
vacuum = true
```

### Benchmarks

For the load test, we used k6 scripts with 100 virtual users who logged in to the platform and answered a problem. The target installation was running redwood in K8S.

You can find the k6 tests here: https://github.com/eduNEXT/openedx-k6-loadtesting

Notice how the 502 errors are reduced to 0 after the fixes
```
1. Default k8s deployments:

     data_received..................: 8.8 MB 64 kB/s
     data_sent......................: 294 kB 2.1 kB/s
     http_req_blocked...............: avg=54ms    min=455ns    med=1.13µs   max=802.08ms p(90)=2.17µs   p(95)=629.69ms
     http_req_connecting............: avg=11.24ms min=0s       med=0s       max=163.75ms p(90)=0s       p(95)=132.52ms
     http_req_duration..............: avg=3.9s    min=126.72ms med=146.21ms max=45.4s    p(90)=18.04s   p(95)=31.13s  
       { expected_response:true }...: avg=3.93s   min=126.72ms med=146.3ms  max=45.4s    p(90)=18.16s   p(95)=31.13s  
     http_req_failed................: 0.98%  ✓ 12       ✗ 1207 
     http_req_receiving.............: avg=23.08ms min=58.45µs  med=208.32µs max=234.44ms p(90)=129.57ms p(95)=137.2ms 
     http_req_sending...............: avg=176.7µs min=55.29µs  med=173.53µs max=523.46µs p(90)=246.48µs p(95)=268.91µs
     http_req_tls_handshaking.......: avg=20.57ms min=0s       med=0s       max=374.19ms p(90)=0s       p(95)=223.41ms
     http_req_waiting...............: avg=3.87s   min=126.29ms med=145.79ms max=45.4s    p(90)=17.94s   p(95)=31.01s  
     http_reqs......................: 1219   8.858423/s
     ✓ { status:200 }...............: 1037   7.535837/s
     ✗ { status:403 }...............: 0      0/s
     ✓ { status:502 }...............: 12     0.087204/s
     iteration_duration.............: avg=42.5s   min=5.82µs   med=21.17s   max=1m14s    p(90)=1m13s    p(95)=1m13s   
     iterations.....................: 161    1.16998/s
     vus............................: 3      min=3      max=100
     vus_max........................: 100    min=100    max=100


2. uwsgi tunning for HTTP (http-keepalive + add-header):

     data_received..................: 7.5 MB 61 kB/s
     data_sent......................: 293 kB 2.4 kB/s
     http_req_blocked...............: avg=80.47ms  min=394ns    med=1.11µs   max=1.07s    p(90)=3.96µs   p(95)=785.65ms
     http_req_connecting............: avg=13.88ms  min=0s       med=0s       max=174.52ms p(90)=0s       p(95)=137.79ms
     http_req_duration..............: avg=5.12s    min=126.99ms med=146.76ms max=53.41s   p(90)=24.29s   p(95)=37.64s  
       { expected_response:true }...: avg=5.12s    min=126.99ms med=146.76ms max=53.41s   p(90)=24.29s   p(95)=37.64s  
     http_req_failed................: 0.00%  ✓ 0        ✗ 1012 
     http_req_receiving.............: avg=13.22ms  min=61.54µs  med=211.79µs max=140.49ms p(90)=7.59ms   p(95)=128.48ms
     http_req_sending...............: avg=174.95µs min=68.78µs  med=167.24µs max=1.34ms   p(90)=237.97µs p(95)=258.95µs
     http_req_tls_handshaking.......: avg=26.69ms  min=0s       med=0s       max=503.98ms p(90)=0s       p(95)=242.62ms
     http_req_waiting...............: avg=5.11s    min=126.62ms med=146.3ms  max=53.41s   p(90)=24.29s   p(95)=37.64s  
     http_reqs......................: 1012   8.169564/s
     ✓ { status:200 }...............: 876    7.071677/s
     ✗ { status:403 }...............: 0      0/s
     ✗ { status:502 }...............: 0      0/s
     iteration_duration.............: avg=49.3s    min=5.59µs   med=21.47s   max=1m22s    p(90)=1m21s    p(95)=1m21s   
     iterations.....................: 126    1.017159/s
     vus............................: 3      min=3      max=100
     vus_max........................: 100    min=100    max=100


3. uwsgi tunning for HTTP + master tunning (master + vacuum + py-call-osafterfork)

     data_received..................: 8.6 MB 61 kB/s
     data_sent......................: 305 kB 2.2 kB/s
     http_req_blocked...............: avg=71.83ms  min=443ns    med=1.14µs   max=1.69s    p(90)=2.27µs   p(95)=782.48ms
     http_req_connecting............: avg=11.45ms  min=0s       med=0s       max=157.15ms p(90)=0s       p(95)=133.12ms
     http_req_duration..............: avg=4.14s    min=127.65ms med=139.88ms max=46.6s    p(90)=17.88s   p(95)=33.14s  
       { expected_response:true }...: avg=4.14s    min=127.65ms med=139.88ms max=46.6s    p(90)=17.88s   p(95)=33.14s  
     http_req_failed................: 0.00%  ✓ 0        ✗ 1184 
     http_req_receiving.............: avg=13.53ms  min=64.81µs  med=218.75µs max=261.77ms p(90)=124.93ms p(95)=129.08ms
     http_req_sending...............: avg=174.85µs min=52.74µs  med=173.39µs max=411.8µs  p(90)=235.25µs p(95)=255.89µs
     http_req_tls_handshaking.......: avg=27.81ms  min=0s       med=0s       max=1.15s    p(90)=0s       p(95)=268.69ms
     http_req_waiting...............: avg=4.12s    min=127.27ms med=139.42ms max=46.6s    p(90)=17.88s   p(95)=33.14s  
     http_reqs......................: 1184   8.443182/s
     ✓ { status:200 }...............: 1020   7.273687/s
     ✗ { status:403 }...............: 0      0/s
     ✗ { status:502 }...............: 0      0/s
     iteration_duration.............: avg=43.58s   min=6.57µs   med=21.03s   max=1m18s    p(90)=1m16s    p(95)=1m17s   
     iterations.....................: 153    1.091053/s
     vus............................: 3      min=3      max=100
     vus_max........................: 100    min=100    max=100
```

The fix affects the performance a bit, however, it improves the reliability of the platform and by enabling the master process, the performance is in pair before the changes.

### CODE REVIEW

**Review by DawoudSheraz — COMMENTED** [review]
please add a changelog for this.

**Review by DawoudSheraz — COMMENTED** [review]
Thanks for all the helpful references and context in PR description, much appreciated. Digging into the issue, how often is it reproducible on Learner and/or Authoring side? Looking at some of the provided links, the one cause is usage of http-socket. I did not find any reference in uswgi that indicates this is the default option. The option is not being used by tutor, so I am trying to learn under what circumstances this issue is more apparent.

**Comment by Ian2012** [comment]
Based on our production logs for many of our installations, we've seen the same pattern, when a user answers a problem (POST request) or when an author is updating a course (POST request). It has been a problem since we migrated to Kubernetes.

On production, we tested many scenarios besides the ones in the PR description and we found that the only feasible solution was the one proposed.

**Review by regisb — APPROVED** [review]
This looks great. Can you please just add a few comments to the uwsgi.ini file to explain what the different settings are doing? If not, I'm afraid a future committer will inadvertently remove those.

**Review by DawoudSheraz — APPROVED** [review]

**Comment by Ian2012** [comment]
@regisb thanks, I've added the comments

**Pull request merged**
