### PR TITLE
docs: fix smtp port default value

### PR DESCRIPTION
**Pull request by regisb**
See: https://discuss.overhang.io/t/default-smtp-configuration-timeout/2367

### CODE REVIEW

**Comment by regisb** [comment]
This is ready for review @overhangio/tutor-developers.

**Review by BbrSofiane — APPROVED** [review]
👍🏿

**Comment by BbrSofiane** [comment]
Wait actually does this need to be mentioned in the Changelog?

**Comment by regisb** [comment]
> Wait actually does this need to be mentioned in the Changelog?

No, this is just a documentation change.

Thanks for the review!

**Pull request merged**
