### PR TITLE
update django setting module

### PR DESCRIPTION
**Pull request by tuan-nng**
Use correct variable as seen in the code here
https://github.com/edx/edx-platform/blob/master/manage.py#L104

### CODE REVIEW

**Comment by regisb** [comment]
@tuan-nng Thanks for your interest! However, I'm not sure this change is required, as the `DJANGO_SETTINGS_MODULE` environment variable is already set by the docker entrypoint: https://github.com/overhangio/tutor/blob/master/tutor/templates/build/openedx/bin/docker-entrypoint.sh#L2
I'm going to close this PR. Feel free to re-open if you think this change is nonetheless required.

**Comment by tuan-nng** [comment]
Thanks @regisb. Now I understand the logic there. However, that variable is only available inside the shell session of entry-point. It makes it not obvious when debugging inside the container.
I think we should set it more explicitly inside the dockerfile.

**Comment by regisb** [comment]
Are you proposing that the `DJANGO_SETTINGS_MODULE` environment variable be defined not in the entrypoint, but in the Dockerfile? I believe the reason why it was defined in the entrypoint is that it depends both on the `SETTINGS` and the `SERVICE_VARIANT` environment variables. If I remember correctly, this made it easier to define modular settings.

You can try to make the change, but I suspect there will be far-ranging consequences...

**Comment by tuan-nng** [comment]
Thanks for your explanation. I'll let it as is.

**Pull request closed without merging**
