### PR TITLE
fix: upgrade exim-relay SMTP image to make it work on arm64

### LINKED ISSUE #600: arm64: current SMTP Docker image (devture/exim-relay:4.94.2-r0-4) does not support ARM and should be upgraded
**Bug description**
The current exim-relay (4.94) has no arm64 support, the newer version (4.95 and all its variations) support arm64.
It solved a problem with the smtp container, I'm not sure about other broken functionality but it runs.

https://registry.hub.docker.com/r/devture/exim-relay/tags

**How to reproduce**
Start docker on Ubuntu arm64.

**Environment**
Ubuntu 20.04.4 on arm64 (Thanks @bradenmacdonald !)

**Additional context**
The system is not up yet, there are many issues but once it'll be up I'll be able to test the SMTP functionality to see if it works.

### PR DESCRIPTION
**Pull request by regisb**
Close #600.

### CODE REVIEW

**Comment by yarons** [comment]
This is awesome, thank you!

**Comment by regisb** [comment]
@yarons can you check it works for you?

**Comment by yarons** [comment]
I checked it before suggesting, I made these changes in the respective docker compose to avoid the errors in the SMTP service and when I pulled the correct image the errors disappeared and the service loaded as expected.

**Comment by regisb** [comment]
Nice, thanks! I'm merging this now @overhangio/tutor-developers.

**Comment by yarons** [comment]
@regisb you're awesome, thank you :)

**Pull request merged**
