### PR TITLE
feat:added event routing backend plugin as dependency

### PR DESCRIPTION
**Pull request by ziafazal**
Added event routing backend plugin as dependency

### CODE REVIEW

**Comment by ziafazal** [comment]
@regisb Could you please review this PR?

**Comment by regisb** [comment]
@ziafazal I need some further information. Do you think that all Open edX users should have edx-event-routing-backends installed by default on their platform? Why?

**Comment by ziafazal** [comment]
@regisb No I don't think all Open edX users should have edx-event-routing-backends installed. I just want to install it for testing nutmeg on https://nutmeg.demo.overhang.io/. So it would be just a local dependency for https://nutmeg.demo.overhang.io/ instance.

**Comment by regisb** [comment]
In that case, I suggest that you close this PR and instead add the edx-event-routing-backends just in the demo platform, very much in the spirit of [this PR](https://github.com/overhangio/nutmeg-demo/pull/11).

**Comment by ziafazal** [comment]
Closing this PR in favour of [this](https://github.com/overhangio/nutmeg-demo/pull/13) one.

**Pull request closed without merging**
